/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118848-g94beaf4872-20250317"
#endif /* AVUTIL_FFVERSION_H */
